### PR TITLE
Add test with a terminal block invalid wrt EE

### PR DESCRIPTION
**Pull request by mkalinin**
cc @marioevz

### CODE REVIEW

**Review by g11tech — APPROVED** [review]
LGTM!

**Comment by marioevz** [comment]
Looks fine, but from what I understood from the comment in interop is that there should be at least another PoW block between `Bn` and `INV_TB` which is also invalid.
Either way this is complicated test case setup, so I need to check Marius' node implementation in hive to see if we can achieve this.

**Comment by mkalinin** [comment]
> Looks fine, but from what I understood from the comment in interop is that there should be at least another PoW block between `Bn` and `INV_TB` which is also invalid.
> Either way this is complicated test case setup, so I need to check Marius' node implementation in hive to see if we can achieve this.

Sure, from the most recent conversation with Marius I understood that one invalid PoW block can be served by a simulator but no more. IMO, having only the terminal block `INVALID` should be enough for this test.

**Review by marioevz — APPROVED** [review]
LGTM, I will be attempting to implement these in the coming days.

**Pull request merged**
